routes/web.php
<?php

use Admin\MenuController;
use Admin\AuthorController;
use Admin\PublisherController;
use Admin\CategoryController;
use Admin\ProductController;
use Admin\BookFormatController;
use Admin\TestimonialController;
use Admin\BookLanguageController;
use App\Http\Controllers\Admin\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () { return view('home'); });
Route::get('/', [HomeController::class,'index'])->name('home');
Route::get('/publishers', [HomeController::class,'publisher'])->name('publisher');
Route::get('/publisher/details/{id}', [HomeController::class,'publishe_details'])->name('publisher.details');

Route::get('/author', [HomeController::class,'authors'])->name('author');
Route::get('/author/details/{id}', [HomeController::class,'authorDetails'])->name('authorDetails');
Route::get('/contact',[HomeController::class,'contactPage'])->name('contact');
Route::get('product/details/{id}',[HomeController::class,'product_details'])->name('product.details');
Route::post('product/details/variation_product_search',[HomeController::class,'variant_product'])->name('variant.search');





Route::get('login', [LoginController::class,'showLoginForm'])->name('login');
Route::post('login', [LoginController::class,'login']);
Route::post('register', [RegisterController::class,'register']);

Route::get('password/forget',  function () {
	return view('pages.forgot-password');
})->name('password.forget');
Route::post('password/email', [ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ResetPasswordController::class,'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class,'reset'])->name('password.update');


Route::group(['middleware' => 'auth'], function(){
	// logout route
	Route::get('/logout', [LoginController::class,'logout']);
	Route::get('/clear-cache', [HomeController::class,'clearCache']);
	// dashboard route
    Route::get('/dashboard',[DashboardController::class,'showDashboard'])->name('dashboard');

	//only those have manage_user permission will get access
	Route::group(['middleware' => 'can:manage_user'], function(){
	    Route::get('/users', [UserController::class,'index']);
	    Route::get('/user/get-list', [UserController::class,'getUserList']);
		Route::get('/user/create', [UserController::class,'create']);
		Route::post('/user/create', [UserController::class,'store'])->name('create-user');
		Route::get('/user/{id}', [UserController::class,'edit']);
		Route::post('/user/update', [UserController::class,'update']);
		Route::get('/user/delete/{id}', [UserController::class,'delete']);
	});

	//only those have manage_role permission will get access
	Route::group(['middleware' => 'can:manage_role|manage_user'], function(){
		Route::get('/roles', [RolesController::class,'index']);
		Route::get('/role/get-list', [RolesController::class,'getRoleList']);
		Route::post('/role/create', [RolesController::class,'create']);
		Route::get('/role/edit/{id}', [RolesController::class,'edit']);
		Route::post('/role/update', [RolesController::class,'update']);
		Route::get('/role/delete/{id}', [RolesController::class,'delete']);
	});

	//only those have manage_permission permission will get access
	Route::group(['middleware' => 'can:manage_permission|manage_user'], function(){
		Route::get('/permission', [PermissionController::class,'index']);
		Route::get('/permission/get-list', [PermissionController::class,'getPermissionList']);
		Route::post('/permission/create', [PermissionController::class,'create']);
		Route::get('/permission/update', [PermissionController::class,'update']);
		Route::get('/permission/delete/{id}', [PermissionController::class,'delete']);
	});

    //only those have manage_menu permission will get access
    Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_menu'], function(){
		Route::get('/menu/get-list', [UserController::class,'getMenuList']);
		Route::resource('menu',MenuController::class);
    });
    //only those have manage_author permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_author'], function(){
        Route::resource('authors',AuthorController::class);
		Route::get('authors/delete/{id}',[App\Http\Controllers\Admin\AuthorController::class,'delete'])->name('authors.delete');
		Route::resource('authors',AuthorController::class);
	});

	//only those have manage_publisher permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_publisher'], function(){
		Route::get('publisher/delete/{id}',[App\Http\Controllers\Admin\PublisherController::class,'delete'])->name('publisher.delete');
		Route::resource('publisher',PublisherController::class);
	});
   //only those have manage_category permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_category'], function(){
		Route::get('category/delete/{id}',[App\Http\Controllers\Admin\CategoryController::class,'delete'])->name('category.delete');
		Route::resource('categories',CategoryController::class);
	});

	//only those have manage_category permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_category'], function(){
		Route::post('product/combination',[App\Http\Controllers\Admin\ProductController::class,'make_combination'])->name('products.combination');
		Route::post('product/update',[App\Http\Controllers\Admin\ProductController::class,'productUpdate'])->name('products.updateProduct');
		Route::get('products/stock',[App\Http\Controllers\Admin\ProductController::class,'product_stock'])->name('products.stock');
		Route::get('products/duplicate/{id}',[App\Http\Controllers\Admin\ProductController::class,'product_duplicate'])->name('products.duplicate');
		Route::resource('products',ProductController::class);
	});

	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_testimonial'], function(){
		Route::resource('testimonials',TestimonialController::class);
	});

	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_book_format'], function(){
		Route::resource('book_formats',BookFormatController::class);
	});

	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_language'], function(){
		Route::resource('languages',BookLanguageController::class);
	});
	
	
	

	// get permissions
	Route::get('get-role-permissions-badge', [PermissionController::class,'getPermissionBadgeByRole']);
});


//Route::get('/register', function () { return view('pages.register'); });

app/Http/Controllers/Admin/AuthorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Auther;
use Auth;
use Image;

class AuthorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $author_all = Auther::where('status',true)->get();
        return view('backend.author.index',compact('author_all'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.author.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name'     => 'required | string | max:100',
            'details'    => 'required | string | max:2000',
            'image' => 'required | image |mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withInput()->with('error', $validator->messages()->first());
        }

        $input = $request->all();
        $input['status'] = true;
        $input['user_id'] = Auth::id();

        $image = $request->file('image');
        if($image){
            $input['image'] = time().'.'.$image->extension();
     
            $destinationPath = public_path('/backend/author');
            $img = Image::make($image->path());
            $success = $img->resize(300, 300, function ($constraint) {
                $constraint->aspectRatio();
            })->save($destinationPath.'/'.$input['image']);
        }

        try
        {
            Auther::create($input);
            return redirect()->route('authors.index')->with('success','Author added successfully');

        }catch (\Exception $e) {
            $bug = $e->getMessage();
            return redirect()->back()->with('error', $bug);

        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $author = Auther::find($id);
        return view('backend.author.edit',compact('author'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'name'     => 'required | string | max:100',
            'details'    => 'required | string | max:2000',
            'image' => 'image |mimes:jpeg,png,jpg,gif,svg|max:2048'
        ]);

        if($validator->fails()) {
            return redirect()->back()->withInput()->with('error', $validator->messages()->first());
        }

        $input = $request->all();
        $author = Auther::find($id);
        if($request->file('image') != null){
            $image = $request->file('image');
            if($image){
                $input['image'] = time().'.'.$image->extension();
        
                $destinationPath = public_path('/backend/author');
                $img = Image::make($image->path());
                $success = $img->resize(300, 300, function ($constraint) {
                    $constraint->aspectRatio();
                })->save($destinationPath.'/'.$input['image']);
                if($success){
                    $old_image = $destinationPath.'/'.$author->image;
                    if (file_exists($old_image)) {
                        @unlink($old_image);
                    }
                }
            }

        }else{
            $input['image'] = $author->image;
        }

        try
        {
            $author->update($input);
            return redirect()->route('authors.index')->with('success','Author updated successfully');

        }catch (\Exception $e) {
            $bug = $e->getMessage();
            return redirect()->back()->with('error', $bug);

        }
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete($id)
    {
        $author = Auther::find($id);
        $destinationPath = public_path('/backend/author');
        $old_image = $destinationPath.'/'.$author->image;
            if (file_exists($old_image)) {
                @unlink($old_image);
            }
        try
        {
            $author->delete();
            return redirect()->route('authors.index')->with('success','Author deleted successfully');

        }catch (\Exception $e) {
            $bug = $e->getMessage();
            return redirect()->back()->with('error', $bug);

        }     
    }
}

resources/views/backend/author/create.blade.php
@extends('layouts.main')
@section('title', 'Authors')
@section('content')
    
<div class="container-fluid">
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="ik ik-user-plus bg-blue"></i>
                <div class="d-inline">
                    <h5>{{ __('Add Authors')}}</h5>
                    <span>{{ __('Create new authors')}}</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <nav class="breadcrumb-container" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{url('dashboard')}}"><i class="ik ik-home"></i></a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">{{ __('Add Authors')}}</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="row">
    <!-- start message area-->
    @include('include.message')
    <!-- end message area-->
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header">
                <h3>{{ __('Add Authors')}}</h3>
            </div>
            <div class="card-body">
                {{ Form::open(array('route'=>['authors.store'],'method'=>'POST','files'=>true)) }}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="name">{{ __('Author Name')}}<span class="text-red">*</span></label>
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="" placeholder="Enter auther name" required>
                                <div class="help-block with-errors"></div>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="details">{{ __('Authers Details')}}<span class="text-red">*</span></label>
                                <textarea class="summernote" name="details"></textarea>
                                <div class="help-block with-errors"></div>

                                @error('details')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label>{{ __('Upload Image') }}<span class="text-red">*</span></label>
                                <input type="file" name="image" class="file-upload-default" onchange="loadFile(event)">
                                <div class="input-group col-xs-12">
                                    <input type="text" name="photo" class="form-control file-upload-info" disabled placeholder="Upload Image">
                                    <span class="input-group-append">
                                    <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                                    </span>
                                </div>
                                <img id="output" width="20%" style="margin-top:5px;" />

                                <div class="help-block with-errors"></div>
                                @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>


                        <div class="col-md-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">{{ __('Submit')}}</button>
                            </div>
                        </div>
                    </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
</div>
<!-- push external js -->
@endsection

resources/views/backend/author/edit.blade.php
@extends('layouts.main')
@section('title', 'Author | Update')
@section('content')
    
<div class="container-fluid">
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <i class="ik ik-user-plus bg-blue"></i>
                <div class="d-inline">
                    <h5>{{ __('Update Authors')}}</h5>
                    <span>{{ __('Update authors')}}</span>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <nav class="breadcrumb-container" aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="{{url('dashboard')}}"><i class="ik ik-home"></i></a>
                    </li>
                    <li class="breadcrumb-item">
                        <a href="#">{{ __('Update Authors')}}</a>
                    </li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="row">
    <!-- start message area-->
    @include('include.message')
    <!-- end message area-->
    <div class="col-md-12">
        <div class="card ">
            <div class="card-header">
                <h3>{{ __('Add Authors')}}</h3>
            </div>
            <div class="card-body">
                {{ Form::open(array('route'=>['authors.update',$author->id],'method'=>'PUT','files'=>true)) }}
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="name">{{ __('Author Name')}}<span class="text-red">*</span></label>
                                <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $author->name }}" placeholder="Enter auther name" required>
                                <div class="help-block with-errors"></div>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="details">{{ __('Authers Details')}}<span class="text-red">*</span></label>
                                <textarea class="summernote" name="details">{!! $author->details !!}</textarea>
                                <div class="help-block with-errors"></div>

                                @error('details')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label>{{ __('Old Image') }}</label><br>
                                <img src="{{ asset('/backend/author/'.$author->image) }}" alt="">
                            </div>

                            <div class="form-group">
                                <label>{{ __('Upload Image') }}</label>
                                <input type="file" name="image" class="file-upload-default" onchange="loadFile(event)">
                                <div class="input-group col-xs-12">
                                    <input type="text" name="photo" class="form-control file-upload-info" disabled placeholder="Upload Image">
                                    <span class="input-group-append">
                                    <button class="file-upload-browse btn btn-primary" type="button">Upload</button>
                                    </span>
                                </div>
                                <img id="output" width="20%" style="margin-top:5px;" />

                                <div class="help-block with-errors"></div>
                                @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary">{{ __('Submit')}}</button>
                            </div>
                        </div>
                    </div>

                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
</div>
<!-- push external js -->
@endsection

resources/views/backend/author/index.blade.php
@extends('layouts.main')
@section('title', 'Author | List')
@section('content')
    
    <div class="container-fluid">
    	<div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="ik ik-users bg-blue"></i>
                        <div class="d-inline">
                            <h5>{{ __('Author')}}</h5>
                            <span>{{ __('List of Author')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <nav class="breadcrumb-container" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('dashboard')}}"><i class="ik ik-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">{{ __('Author')}}</a>
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- start message area-->
            @include('include.message')
            <!-- end message area-->
            <div class="col-md-12">
                <div class="card p-3">
                    <div class="card-header"><h3>{{ __('Author')}}</h3></div>
                    <div class="card-body">
                        <table id="data_table" class="table">
                            <thead>
                                <tr>
                                    <th>{{ __('Sl')}}</th>
                                    <th>{{ __('Name')}}</th>
                                    <th>{{ __('Image') }}</th>
                                    <th>{{ __('Description') }}</th>
                                    <th>{{ __('Status') }}</th>
                                    <th style="text-align:right;">{{ __('Action')}}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($author_all as $key=>$item)
                                     <tr>
                                         <td>{{ $key+1 }}</td>
                                         <td>{{ $item->name }}</td>
                                         <td>
                                            <img src="{{ asset('/backend/author/'.$item->image) }}" class="table-user-thumb" alt="">
                                         </td>
                                         <td>{!! $item->details !!}</td>
                                         <td>
                                             @if ($item->status == 1)
                                               <span class="badge badge-success m-1">Active</span>
                                             @else
                                               <span class="badge badge-danger m-1">Inactive</span>
                                             @endif
                                         </td>
                                         <td>
                                            <div class="table-actions">
                                                <a href="{{ route('authors.edit',$item->id) }}"><i class="ik ik-edit-2 text-green"></i></a>
                                                <a href="{{ route('authors.delete',$item->id) }}" onclick="return confirmDelete()"><i class="ik ik-trash-2 text-red"></i></a>
                                            </div>
                                         </td>
                                     </tr> 
                                @empty
                                    No data found
                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <!-- push external js -->
@endsection