routes/web.php
<?php

use Admin\MenuController;
use Admin\AuthorController;
use Admin\PublisherController;
use Admin\CategoryController;
use Admin\ProductController;
use Admin\BookFormatController;
use Admin\TestimonialController;
use Admin\BookLanguageController;
use App\Http\Controllers\Admin\DashboardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use App\Http\Controllers\Auth\ForgotPasswordController;
use App\Http\Controllers\Auth\ResetPasswordController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\PermissionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Route::get('/', function () { return view('home'); });
Route::get('/', [HomeController::class,'index'])->name('home');
Route::get('/publishers', [HomeController::class,'publisher'])->name('publisher');
Route::get('/publisher/details/{id}', [HomeController::class,'publishe_details'])->name('publisher.details');

Route::get('/author', [HomeController::class,'authors'])->name('author');
Route::get('/author/details/{id}', [HomeController::class,'authorDetails'])->name('authorDetails');
Route::get('/contact',[HomeController::class,'contactPage'])->name('contact');
Route::get('product/details/{id}',[HomeController::class,'product_details'])->name('product.details');
Route::post('product/details/variation_product_search',[HomeController::class,'variant_product'])->name('variant.search');





Route::get('login', [LoginController::class,'showLoginForm'])->name('login');
Route::post('login', [LoginController::class,'login']);
Route::post('register', [RegisterController::class,'register']);

Route::get('password/forget',  function () {
	return view('pages.forgot-password');
})->name('password.forget');
Route::post('password/email', [ForgotPasswordController::class,'sendResetLinkEmail'])->name('password.email');
Route::get('password/reset/{token}', [ResetPasswordController::class,'showResetForm'])->name('password.reset');
Route::post('password/reset', [ResetPasswordController::class,'reset'])->name('password.update');


Route::group(['middleware' => 'auth'], function(){
	// logout route
	Route::get('/logout', [LoginController::class,'logout']);
	Route::get('/clear-cache', [HomeController::class,'clearCache']);
	// dashboard route
    Route::get('/dashboard',[DashboardController::class,'showDashboard'])->name('dashboard');

	//only those have manage_user permission will get access
	Route::group(['middleware' => 'can:manage_user'], function(){
	    Route::get('/users', [UserController::class,'index']);
	    Route::get('/user/get-list', [UserController::class,'getUserList']);
		Route::get('/user/create', [UserController::class,'create']);
		Route::post('/user/create', [UserController::class,'store'])->name('create-user');
		Route::get('/user/{id}', [UserController::class,'edit']);
		Route::post('/user/update', [UserController::class,'update']);
		Route::get('/user/delete/{id}', [UserController::class,'delete']);
	});

	//only those have manage_role permission will get access
	Route::group(['middleware' => 'can:manage_role|manage_user'], function(){
		Route::get('/roles', [RolesController::class,'index']);
		Route::get('/role/get-list', [RolesController::class,'getRoleList']);
		Route::post('/role/create', [RolesController::class,'create']);
		Route::get('/role/edit/{id}', [RolesController::class,'edit']);
		Route::post('/role/update', [RolesController::class,'update']);
		Route::get('/role/delete/{id}', [RolesController::class,'delete']);
	});

	//only those have manage_permission permission will get access
	Route::group(['middleware' => 'can:manage_permission|manage_user'], function(){
		Route::get('/permission', [PermissionController::class,'index']);
		Route::get('/permission/get-list', [PermissionController::class,'getPermissionList']);
		Route::post('/permission/create', [PermissionController::class,'create']);
		Route::get('/permission/update', [PermissionController::class,'update']);
		Route::get('/permission/delete/{id}', [PermissionController::class,'delete']);
	});

    //only those have manage_menu permission will get access
    Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_menu'], function(){
		Route::get('/menu/get-list', [UserController::class,'getMenuList']);
		Route::resource('menu',MenuController::class);
    });
    //only those have manage_author permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_author'], function(){
        Route::resource('authors',AuthorController::class);
		Route::get('authors/delete/{id}',[App\Http\Controllers\Admin\AuthorController::class,'delete'])->name('authors.delete');
		Route::resource('authors',AuthorController::class);
	});

	//only those have manage_publisher permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_publisher'], function(){
		Route::get('publisher/delete/{id}',[App\Http\Controllers\Admin\PublisherController::class,'delete'])->name('publisher.delete');
		Route::resource('publisher',PublisherController::class);
	});
   //only those have manage_category permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_category'], function(){
		Route::get('category/delete/{id}',[App\Http\Controllers\Admin\CategoryController::class,'delete'])->name('category.delete');
		Route::resource('categories',CategoryController::class);
	});

	//only those have manage_category permission will get access
	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_category'], function(){
		Route::post('product/combination',[App\Http\Controllers\Admin\ProductController::class,'make_combination'])->name('products.combination');
		Route::post('product/update',[App\Http\Controllers\Admin\ProductController::class,'productUpdate'])->name('products.updateProduct');
		Route::get('products/stock',[App\Http\Controllers\Admin\ProductController::class,'product_stock'])->name('products.stock');
		Route::get('products/duplicate/{id}',[App\Http\Controllers\Admin\ProductController::class,'product_duplicate'])->name('products.duplicate');
		Route::resource('products',ProductController::class);
	});

	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_testimonial'], function(){
		Route::resource('testimonials',TestimonialController::class);
	});

	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_book_format'], function(){
		Route::resource('book_formats',BookFormatController::class);
	});

	Route::group(['prefix' => 'dashboard','middleware' => 'can:manage_language'], function(){
		Route::resource('languages',BookLanguageController::class);
	});
	
	
	

	// get permissions
	Route::get('get-role-permissions-badge', [PermissionController::class,'getPermissionBadgeByRole']);
});


//Route::get('/register', function () { return view('pages.register'); });

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use App\Publisher;
use App\Auther;
use App\BookLanguage;
use App\BookFormat;
use App\Category;
use App\Product;
use App\ProductStock;
use Image;
use Auth;
use PhpParser\Node\Stmt\TryCatch;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all_products = Product::orderBy('id','DESC')->get();
        return view('backend.product.index',compact('all_products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $publisher_all = Publisher::where('status',true)->get();
        $author_all = Auther::where('status',true)->get();
        $bokk_formats = BookFormat::where('status',true)->get();
        $book_languages = BookLanguage::where('status',true)->get();
        $parent_categories = Category::where('parent_id',0)->where('status',true)->get();
        return view('backend.product.create',compact('publisher_all','author_all','bokk_formats','book_languages','parent_categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //return $request->all();
        $data = $request->all();
        $data['user_id'] = Auth::id();
        $data['status'] = true;
        $data['num_of_sale'] = 0;

        if($request->discount_price != null){
            if($request->discount_type == 1){
                $data['discount'] = 'Flat';
                $data['discount_price'] = $request->discount_price;
            }else{
                $data['discount'] = 'Percentage';
                $data['discount_price'] = $request->unit_price * ($request->discount_price/100);
            }
        }else{
            $data['discount'] = "";
            $data['discount_type'] = 0;
        }
        
        $data['slug'] = preg_replace('/[^A-Za-z0-9\-]/', '', str_replace(' ', '-', $request->title)).'-'.Str::random(5);
        if($request->has('language') && count($request->language) > 0){
            $data['language'] = json_encode($request->language);
        }
        else {
            $language = array();
            $data['language'] = json_encode($language);
        }

        if($request->has('book_format') && count($request->book_format) > 0){
            $data['book_format'] = json_encode($request->book_format);
        }
        else {
            $book_format = array();
            $data['book_format'] = json_encode($book_format);
        }

        if($request->has('variant') && count($request->variant) > 0){
            $data['variant'] = json_encode($request->variant);
        }
        else {
            $variant = array();
            $data['variant'] = json_encode($variant);
        }
        

        if($request->has('image')){
            $image = $request->file('image');
            if($image){
                $data['image'] = time().'.'.$image->extension();
         
                $destinationPath = public_path('/backend/products');
                $img = Image::make($image->path());
                $success = $img->resize(800, 1130, function () {
                })->save($destinationPath.'/'.$data['image']);
            }
        }
    

        try
        {
            $product = Product::create($data);
            $variant = [];
            foreach($request->variant as $key=>$var){

                $variant['user_id'] = Auth::id();
                $variant['product_id'] = $product->id;
                $variant['variant'] = $var;

                if($request->quantity[$key] == null){
                    $variant['quantity'] = $request->min_qty;
                }else{
                    $variant['quantity'] = $request->quantity[$key];
                }

                if($request->price[$key] == null){
                    if($request->discount_price != null) {
                        if($request->discount_type == 1){
                            $dis_price = $request->discount_price;
                        }else{
                            $dis_price = $request->unit_price * ($request->discount_price/100);
                        }
                        $variant['price'] = $dis_price;
                     } else {
                        $variant['price'] = $request->unit_price;
                     } 
                }else{
                    $variant['price'] = $request->price[$key];
                }
                $variant['status'] = true;
                ProductStock::create($variant);
            }
            return redirect()->route('products.index')->with('success','Product added successfully');

        }catch (\Exception $e) {
            $bug = $e->getMessage();
            return redirect()->back()->with('error', $bug);
        }
        
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $publisher_all = Publisher::where('status',true)->get();
        $author_all = Auther::where('status',true)->get();
        $bokk_formats = BookFormat::where('status',true)->get();
        $book_languages = BookLanguage::where('status',true)->get();
        $parent_categories = Category::where('parent_id',0)->where('status',true)->get();
        $product = Product::findOrFail($id);
        return view('backend.product.edit',compact('publisher_all','author_all','bokk_formats','book_languages','parent_categories','product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function productUpdate(Request $request)
    {
        //return $request->all();
        $data = $request->all();
        $product = Product::findOrFail($request->product_id);
        if($request->discount_price != null){
            if($request->discount_type == 1){
                $data['discount'] = 'Flat';
                $data['discount_price'] = $request->discount_price;
            }else{
                $data['discount'] = 'Percentage';
                $data['discount_price'] = $request->unit_price * ($request->discount_price/100);
            }
        }else{
            $data['discount'] = "";
            $data['discount_type'] = 0;
        }

        if($request->has('language') && count($request->language) > 0){
            $data['language'] = json_encode($request->language);
        }
        else {
            $language = array();
            $data['language'] = json_encode($language);
        }

        if($request->has('book_format') && count($request->book_format) > 0){
            $data['book_format'] = json_encode($request->book_format);
        }
        else {
            $book_format = array();
            $data['book_format'] = json_encode($book_format);
        }

        if($request->has('variant') && count($request->variant) > 0){
            $data['variant'] = json_encode($request->variant);
        }
        else {
            $variant = array();
            $data['variant'] = json_encode($variant);
        }

        if($request->file('image') != null){
            $image = $request->file('image');
            if($image){
                $data['image'] = time().'.'.$image->extension();
                $destinationPath = public_path('/backend/products');
                $img = Image::make($image->path());
                $success = $img->resize(800, 1130, function () {
                })->save($destinationPath.'/'.$data['image']);

                if($success){
                    $old_image = $destinationPath.'/'.$product->image;
                    if (file_exists($old_image)) {
                        @unlink($old_image);
                    }
                }
            }

        }else{
            $input['image'] = $product->image;
        }



        try
        {
            $product->update($data);
            $variant = [];
            foreach($request->variant as $key=>$var){
                //previous variant delete
                $old_variants = ProductStock::where('product_id',$request->product_id)->get();
                foreach($old_variants as $key=>$old_variant){
                    $old_variant_data[] = $old_variant->variant;

                    if(!(in_array($old_variant->variant,$request->variant))){
                        ProductStock::where([
                           ['product_id',$request->product_id],
                           ['variant',$old_variant->variant]
                        ])->delete();
                    }
                }

                $variant['user_id'] = Auth::id();
                $variant['product_id'] = $product->id;
                $variant['variant'] = $var;

                if($request->quantity[$key] == null){
                    $variant['quantity'] = $request->min_qty;
                }else{
                    $variant['quantity'] = $request->quantity[$key];
                }

                if($request->price[$key] == null){
                    if($request->discount_price != null) {
                        if($request->discount_type == 1){
                            $dis_price = $request->discount_price;
                        }else{
                            $dis_price = $request->unit_price * ($request->discount_price/100);
                        }

resources/views/backend/product/index.blade.php
@extends('layouts.main')
@section('title', 'Products')
@section('content')
    
    <div class="container-fluid">
    	<div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="ik ik-users bg-blue"></i>
                        <div class="d-inline">
                            <h5>{{ __('Products')}}</h5>
                            <span>{{ __('List of Product')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <nav class="breadcrumb-container" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('dashboard')}}"><i class="ik ik-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">{{ __('Product')}}</a>
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- start message area-->
            @include('include.message')
            <!-- end message area-->
            <div class="col-md-12">
                <div class="card p-3">
                    <div class="card-header"><h3>{{ __('Product')}}</h3></div>
                    <div class="card-body">
                        <table id="data_table" class="table">
                            <thead>
                                <tr>
                                    <th width="10%">{{ __('Sl')}}</th>
                                    <th width="20%">{{ __('Name')}}</th>
                                    <th width="10%">{{ __('Author')}}</th>
                                    <th width="10%">{{ __('Publisher')}}</th>
                                    <th width="10%">{{ __('Category')}}</th>
                                    <th width="10%">{{ __('Image') }}</th>
                                    <th width="10%">{{ __('Price') }}</th>
                                    <th width="10%">{{ __('Status') }}</th>
                                    <th width="10%">{{ __('Action') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($all_products as $key=>$product)
                                    <tr>
                                        <td>
                                            {{ $key+1 }}
                                        </td>
                                        <td>{{ $product->title }}</td>
                                        <td>{{ $product->author->name }}</td>
                                        <td>{{ $product->publisher->name }}</td>
                                        <td>{{ $product->category->name }}</td>
                                        <td>
                                            <img src="{{ asset('/backend/products/'.$product->image) }}" alt="" style="width:50%;">
                                        </td>
                                        <td>
                                            Price: {{ $product->unit_price }}</br>
                                            @if($product->discount_price)
                                                  Discount Price: {{ $product->discount_price }}
                                            @endif
                                        </td>
                                        <td>
                                            @if ($product->status == 1)
                                               <span class="badge badge-success m-1">Active</span>
                                             @else
                                               <span class="badge badge-danger m-1">Inactive</span>
                                             @endif
                                        </td>
                                        <td>
                                            <div class="table-actions">
                                                <a href="{{ route('products.duplicate',$product->id) }}"><i class="ik ik-external-link text-orange"></i></a>
                                                <a href="{{ route('products.edit',$product->id) }}"><i class="ik ik-edit-2 text-green"></i></a>
                                                <a href="{{ url('product/details',$product->slug) }}"><i class="ik ik-eye text-green"></i></a>
                                                <a id="edit_button" data-id="{{ $product->id }}"><i class="ik ik-trash-2 text-red"></i></a>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                            
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <!-- push external js -->
@endsection

resources/views/backend/product/stock.blade.php
@extends('layouts.main')
@section('title', 'Products Stock')
@section('content')
    
    <div class="container-fluid">
    	<div class="page-header">
            <div class="row align-items-end">
                <div class="col-lg-8">
                    <div class="page-header-title">
                        <i class="ik ik-users bg-blue"></i>
                        <div class="d-inline">
                            <h5>{{ __('Products')}}</h5>
                            <span>{{ __('Stock of Product')}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <nav class="breadcrumb-container" aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a href="{{route('dashboard')}}"><i class="ik ik-home"></i></a>
                            </li>
                            <li class="breadcrumb-item">
                                <a href="#">{{ __('Product Stock')}}</a>
                            </li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <div class="row">
            <!-- start message area-->
            @include('include.message')
            <!-- end message area-->
            <div class="col-md-12">
                <div class="card p-3">
                    <div class="card-header"><h3>{{ __('Product')}}</h3></div>
                    <div class="card-body">
                        <table id="data_table" class="table">
                            <thead>
                                <tr>
                                    <th width="10%">{{ __('Sl')}}</th>
                                    <th width="30%">{{ __('Book Info')}}</th>
                                    <th width="20%">{{ __('Image') }}</th>
                                    <th width="50%">{{ __('Variant + Stock') }}</th>
                                    
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($all_products as $key=>$product)
                                    <tr>
                                        <td>
                                            {{ $key+1 }}
                                        </td>
                                        <td>
                                            <p><b>{{ $product->title }}</b></p>
                                            <p>Auther : {{ $product->author->name }}</p>
                                            <p>Publisher : {{ $product->publisher->name }}</p>
                                        </td>
                                        <td>
                                            <img src="{{ asset('/backend/products/'.$product->image) }}" alt="" style="width:20%;">
                                        </td>
                                        <td>
                                            <table width="100%">
                                                <tbody>
                                                    @foreach (json_decode($product->stocks) as $key => $stock)
                                                    <tr>
                                                        <td>{{ $stock->variant }}</td>
                                                        <td>{{ $stock->price }}</td>
                                                        <td>{{ $stock->quantity }}</td>
                                                    </tr>
                                                    @endforeach
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
    <!-- push external js -->
@endsection